### ISSUE TITLE
Built in stats page, stats tab not showing statistics. 

### ISSUE THREAD

**Issue by abclution** [johnson442/custom-zyxel-firmware#2]
VMG-1312-B10A in bridge (actually only using it as a modem, Mikrotik device doing the PPPOE connection) mode, also using Annex M

Current Firmware Version: V17-jumbo-tel-x6-stats-cmd

The bonus stat server you included, at least on of its pages is not quite updating properly for me.
Stats tab looks like this, other pages seem to be updating correctly

![image](https://user-images.githubusercontent.com/10130237/68069656-d4800b00-fd6b-11e9-98fa-6c1e569863b9.png)

My Zyxel Stat page looks like this

![image](https://user-images.githubusercontent.com/10130237/68069680-14df8900-fd6c-11e9-8323-5b9815d1ca0b.png)

Haven't rebooted yet but am going to try it just in case

**Comment by abclution** [comment]
Ok, a reboot didnt clear anything. I am attaching the /data/stats file in case there is any clues there.
[stats.txt](https://github.com/johnson442/custom-zyxel-firmware/files/3800363/stats.txt)

**Comment by abclution** [comment]
Also, no idea how to access the /data/boot-cmds.sh for updating or editing. 

In telnet, there is no filesystem access, ftp shows connectivity to the /mnt folder but no ability the cwd to any other folder.

Sorry to be annoying.

**Comment by johnson442** [comment]
> Also, no idea how to access the /data/boot-cmds.sh for updating or editing.
> 
> In telnet, there is no filesystem access, ftp shows connectivity to the /mnt folder but no ability the cwd to any other folder.
>
> Sorry to be annoying.

Not at all! 

Editing the /data/boot-cmds.sh requires gaining full busybox shell, if logged in with admin account via telnet/ssh:
`xtm ; sh`
or
`xtm & sh`

Then `cd` around and edit with `vi`.

Thanks for the stats.txt, have only tested on a VDSL line, so probably a difference in length or order causing issue, will look into it now.

Edit:
Issue was a new empty line with ADSL stats that wasnt dealt with properly, you can edit yourself on a live modem by gaining shell as above:
```
cd /var/tmp/stats
vi index.html
```
2 lines need adding, see https://github.com/johnson442/custom-zyxel-firmware/commit/8af834d144d5e6e6c28720076ec9765c6defd483 for reference. 

If its easier you could download [index.html](https://raw.githubusercontent.com/johnson442/custom-zyxel-firmware/master/stats-staging/stats-server/index.html) and place on usb stick then:
`cp /mnt/usb1_1/index.html /var/tmp/stats`

Will not survive a reboot, but would be great if you could test before I rebuild images.

**Comment by johnson442** [comment]
Heres a binary with the changes, tested to boot and have correct features:
[1312-B10A-17-jumbo-tel-x6-stats1.1-cmd.zip](https://github.com/johnson442/custom-zyxel-firmware/files/3802281/1312-B10A-17-jumbo-tel-x6-stats1.1-cmd.zip)

**Comment by abclution** [comment]
Hi, I am trying out the new firmware will report in a couple hours what works and doesn't.

Also, regarding testing the changes before building the firmware, sure, I'm in. Had huge thunderstorms last two days so no firmware shenanigans at that time for obvious reasons. :P

**Comment by johnson442** [comment]
Ace! thanks for testing.
